# Generated by Django 3.1.2 on 2020-10-20 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_auto_20201020_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='correct',
            field=models.CharField(choices=[('option1', 'option1'), ('option2', 'option2'), ('option3', 'option3'), ('option4', 'option4'), ('None', 'None')], default='None', max_length=100),
        ),
    ]
